
Usage: make options...

Option          Description
------          -----------
clean           Clean build directories of projects
pull            Pull latest source code including submodules
build           Build projects with tests
build-fast      Build projects without tests
release         Release a new version for projects
publish         Publish libraries to Maven local
publish-remote  Publish libraries to Maven Central staging
publish-central Publish libraries to Maven Central (auto-release)

