/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("io.documentnode.epub4j.java-application-conventions")
}

dependencies {
  implementation(project(":epub4j-core"))

  implementation("net.sourceforge.htmlcleaner:htmlcleaner:2.2") {
    exclude("org.jdom", "jdom")
    exclude("org.apache.ant", "ant")
  }
  implementation("commons-vfs:commons-vfs:1.0")
  implementation("commons-lang:commons-lang:2.4")
  implementation("commons-io:commons-io:2.0.1")
}

application {
  // Define the main class for the application.
  mainClass.set("io.documentnode.epub4j.app.App")
}
