/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("io.documentnode.epub4j.java-application-conventions")
}

dependencies {
  implementation(project(":epub4j-core"))
}

application {
  // Define the main class for the application.
  mainClass.set("io.documentnode.epub4j.examples.Example")
}
